### ISSUE TITLE
Select and sync multiple players 

### ISSUE THREAD

**Issue by 80081** [floris-b/lms_tts_notify#6]
I have multiple LMS players, 1 in each room the ability to play a notification on multiple devices sync'd would be great.

**Comment by floris-b** [comment]
At first I made that the players where sync'd but with short alerts sounds or tts messages I did not work reliable.
You can specify multiple players to play the same message with one service call.

**Comment by rjgrandy** [comment]
Is this something you could make an option for? What do you mean by, it didn't work reliable? When I specify multiple players, I can hear a slight offset between the players since they aren't sync'd but are in adjacent rooms, its kind of annoying because it makes it sound like an echo, I would like to use multiple players though.
